#############################################################
## Run the real data analyzes using the tapping data from a 
## subset of 57 patients. The results generated by this  
## script are presented on Section 3 of:
##
## Chaibub Neto et al. (2015) Personalized hypothesis 
## tests for detecting medication response in Parkinson's
## patients using iPhone sensor data. 
#############################################################

require(devtools)
require(rGithubClient)
require(synapseClient)
synapseLogin()

## pointer to this code in github
repo <- getRepo('Sage-Bionetworks/personalized_hypothesis_tests')
thisCode <- getPermlink(repo, 'run_real_data_analysis_tapping_6_25_15.R')

## source functions for shaping the data and running
## the personalized hypotheis tests
sourceRepoFile(repo, 'personalized_hypothesis_tests_functions.R')
hypTestCode <- getPermlink(repo, 'personalized_hypothesis_tests_functions.R')

## load the tapping data on the subset of 57 patients
## that performed at least 30 tapping tasks before medication
## and 30 tapping tasks after medication
tapSubset <- synGet("syn4649829")
load(tapSubset@filePath)

## activity used for this analysis
act <- Activity(name="Simulate Data",
                used=list(tapSubset, list(url=hypTestCode, name=basename(hypTestCode))),
                executed=list(url=thisCode, name=basename(thisCode)))
act <- synStore(act)



## generate random seeds used in the train/test data splits
##
set.seed(123)
splitSeeds <- sample(10000:100000, 100, replace = FALSE)

## select 100 runs, using half of the data for 
## training, and half of the data as test set
## (for the classifier tests)
##
nRuns <- 100
nSplits <- 2

## select the outcome variable, and the extracted
## features to be used in the analyzes
##
respName <- "momentInDayFormat.json.choiceAnswers"
featNames <- colnames(scases)[9:32]

## get the patients ids
##
sel <- unique(scases$healthCode)

## run the UI-tests (based on t- and Wilcoxon's
## rank sum tests)
##
cat("running UI-tests", "\n")
o0 <- RunUITests(sel, scases, sort.by = "none")

## run the classifier test based on the random forest 
## classifier
##
cat("running random forest tests", "\n")
o1 <- RunPerClassTests(sel, nRuns, scases, nSplits, splitSeeds, respName, featNames, 
                       RandomForestTest, refClass = "before")

## run the classifier test based on the extra trees 
## classifier
##
cat("running extra trees tests", "\n")
o2 <- RunPerClassTests(sel, nRuns, scases, nSplits, splitSeeds, respName, featNames, 
                       ExtraTreesTest, refClass = "before")

## run the classifier test based on the logistic 
## regression classifier
##
cat("running logistic regression tests", "\n")
o3 <- RunPerClassTests(sel, nRuns, scases, nSplits, splitSeeds, respName, featNames, 
                       GlmTest)

## run the classifier test based on the penalized logistic 
## regression classifier using elastic-net penalty. We 
## used 3 fold cross-validation for tuning parameter
## optimization because some participants have small
## sample sizes for training the model (around 30)
##
cat("running elastic-net tests", "\n")
o4 <- RunPerClassTests(sel, nRuns, scases, nSplits, splitSeeds, respName, featNames, 
                       EnetTest, alphaGrid = seq(0.1, 0.9, by = 0.1), nfolds = 3)


## save the results
realFile <- file.path(tempdir(), "real_data_analysis_outputs.RData")
save(o0, o1, o2, o3, o4, file = realFile, compress = TRUE)
synReal <- synStore(File(realFile, parentId="syn4649811"), activity=act)
